/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHermesPaperReportRouteImport } from './routes/api/public/hermes-paper-report'
import { Route as ApiPublicHermesOpenPaperTradesRouteImport } from './routes/api/public/hermes-open-paper-trades'
import { Route as ApiPublicHermesIngestRouteImport } from './routes/api/public/hermes-ingest'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHermesPaperReportRoute =
  ApiPublicHermesPaperReportRouteImport.update({
    id: '/api/public/hermes-paper-report',
    path: '/api/public/hermes-paper-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHermesOpenPaperTradesRoute =
  ApiPublicHermesOpenPaperTradesRouteImport.update({
    id: '/api/public/hermes-open-paper-trades',
    path: '/api/public/hermes-open-paper-trades',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHermesIngestRoute = ApiPublicHermesIngestRouteImport.update({
  id: '/api/public/hermes-ingest',
  path: '/api/public/hermes-ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/public/hermes-ingest': typeof ApiPublicHermesIngestRoute
  '/api/public/hermes-open-paper-trades': typeof ApiPublicHermesOpenPaperTradesRoute
  '/api/public/hermes-paper-report': typeof ApiPublicHermesPaperReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/public/hermes-ingest': typeof ApiPublicHermesIngestRoute
  '/api/public/hermes-open-paper-trades': typeof ApiPublicHermesOpenPaperTradesRoute
  '/api/public/hermes-paper-report': typeof ApiPublicHermesPaperReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/public/hermes-ingest': typeof ApiPublicHermesIngestRoute
  '/api/public/hermes-open-paper-trades': typeof ApiPublicHermesOpenPaperTradesRoute
  '/api/public/hermes-paper-report': typeof ApiPublicHermesPaperReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/public/hermes-ingest'
    | '/api/public/hermes-open-paper-trades'
    | '/api/public/hermes-paper-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/public/hermes-ingest'
    | '/api/public/hermes-open-paper-trades'
    | '/api/public/hermes-paper-report'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/public/hermes-ingest'
    | '/api/public/hermes-open-paper-trades'
    | '/api/public/hermes-paper-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicHermesIngestRoute: typeof ApiPublicHermesIngestRoute
  ApiPublicHermesOpenPaperTradesRoute: typeof ApiPublicHermesOpenPaperTradesRoute
  ApiPublicHermesPaperReportRoute: typeof ApiPublicHermesPaperReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes-paper-report': {
      id: '/api/public/hermes-paper-report'
      path: '/api/public/hermes-paper-report'
      fullPath: '/api/public/hermes-paper-report'
      preLoaderRoute: typeof ApiPublicHermesPaperReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes-open-paper-trades': {
      id: '/api/public/hermes-open-paper-trades'
      path: '/api/public/hermes-open-paper-trades'
      fullPath: '/api/public/hermes-open-paper-trades'
      preLoaderRoute: typeof ApiPublicHermesOpenPaperTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes-ingest': {
      id: '/api/public/hermes-ingest'
      path: '/api/public/hermes-ingest'
      fullPath: '/api/public/hermes-ingest'
      preLoaderRoute: typeof ApiPublicHermesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicHermesIngestRoute: ApiPublicHermesIngestRoute,
  ApiPublicHermesOpenPaperTradesRoute: ApiPublicHermesOpenPaperTradesRoute,
  ApiPublicHermesPaperReportRoute: ApiPublicHermesPaperReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
